[package]
name = "framec"
version = "0.6.0"
authors = ["Mark Truluck <mark@frame-lang.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
convert_case = "0.4.0"
downcast-rs = "1.2.0"
exitcode = "1.1.2"
fomat-macros = "0.3.1"
# runtime-fmt = "0.4.1"
structopt = "0.3.21"
wasm-bindgen = "0.2"
yaml-rust = "0.4.5"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
