[package]
name = "framec"
version = "0.7.0"
authors = ["Mark Truluck <mark@frame-lang.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
convert_case = "0.4.0"
downcast-rs = "1.2.0"
exitcode = "1.1.2"
figment = { version = "0.10.6", features = ["yaml"] }
fomat-macros = "0.3.1"
# runtime-fmt = "0.4.1"
serde = { version = "1.0", features = ["serde_derive"] }
serde_yaml = "0.8"
structopt = "0.3.21"
wasm-bindgen = "0.2"
yaml-rust = "0.4.5"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
