codegen:
  common:
    features:
    code:

  rust:
    features:
      follow_rust_naming: true
      generate_action_impl: true
      runtime_support: true
    code:
      actions_prefix:
      actions_suffix: Actions
      action_prefix:
      action_suffix:
      enter_msg: Enter
      exit_msg: Exit
      event_args_suffix: Args
      event_args_method_suffix: _args
      enter_args_member_name: enter_args
      exit_args_member_name: exit_args
      state_args_var: state_args
      state_args_suffix: StateArgs
      state_vars_var_name: state_vars
      state_vars_suffix: StateVars
      state_context_name: StateContext
      state_context_suffix: StateContext
      state_context_var_name: state_context
      state_context_method_suffix: _context
      this_state_context_var_name: this_state_context
      frame_event_args_type_name: FrameEventArgs
      frame_event_message_type_name: FrameMessage
      frame_event_type_name: FrameEvent
      frame_event_return: FrameEventReturn
      frame_event_variable_name: frame_event
      frame_event_args_attribute_name: arguments
      frame_event_message_attribute_name: message
      frame_event_return_attribute_name: ret
      state_var_name: state
      state_handler_name_prefix:
      state_handler_name_suffix: _handler
      state_enum_suffix: State
      state_enum_traits: Clone, Copy, Debug, Eq, Hash, PartialEq, PartialOrd, Ord
      initialize_method_name: initialize
      handle_event_method_name: handle_event
      transition_method_name: transition
      change_state_method_name: change_state
      state_stack_var_name: state_stack
      state_stack_push_method_name: state_stack_push
      state_stack_pop_method_name: state_stack_pop
